# Generated by Django 4.0.4 on 2022-10-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_activity_remove_equipment_user_remove_usertags_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user_name',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
