# Generated by Django 4.1.6 on 2023-02-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_activity_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
